/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kzq_study_JniTest */

#ifndef _Included_com_kzq_study_JniTest
#define _Included_com_kzq_study_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kzq_study_JniTest
 * Method:    mp4toyuv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kzq_study_JniTest_mp4toyuv
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
